In [1]:
#1.Debug the given code

#import pandas as pd
#data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
 #       'Feature2': [5.5, 6.7, 8.9]}
#df = pd.DataFrame(data)
#df['Feature1'] = df['Feature1'].astype(int)  # Error: Cannot convert 'Thirty' to int
#print(df)


#Answer#

import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].replace({"Thirty": 30})
df['Feature1'] = df['Feature1'].astype(int)  

print(df)


import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = pd.to_numeric(df['Feature1'], errors='coerce')  

print(df)

   Feature1  Feature2
0        10       5.5
1        20       6.7
2        30       8.9
   Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       NaN       8.9


In [2]:
#2.
#import pandas as pd

#data = {'A': [1, 2, None],  # Missing value
#        'B': [4, None, 6]}  # Missing value

#df = pd.DataFrame(data)
#mean_value = df.mean()
#df.fillna(mean_value)  # Error: fillna() does not modify in place

#print(df)


#Answer#

import pandas as pd

data = {'A': [1, 2, None],  
        'B': [4, None, 6]}  

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value, inplace = True)  

print(df)

     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [3]:
#3.from sklearn.linear_model import LinearRegression
#import numpy as np

#X = np.array([1, 2, 3, 4, 5])  # Error: X should be 2D
#y = np.array([2, 4, 6, 8, 10])

#model = LinearRegression()
#model.fit(X, y)


#Answer#

from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[1], [2], [3], [4], [5]])  
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

print(model.predict([[12]]))



from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5]).reshape(-1,1)  
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

print(model.predict([[12]]))

[24.]
[24.]


In [4]:
#4.
#from sklearn.preprocessing import StandardScaler
#import numpy as np
#data = np.array([10, 20, 30, 40, 50])  # Error: Should be 2D
#scaler = StandardScaler()
#scaled_data = scaler.fit_transform(data)
#print(scaled_data)


#Answer#


from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50]).reshape(-1, 1)  

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [5]:
#5.
#from sklearn.linear_model import LogisticRegression
#X = [[1, 2], [3, 4], [5, 6]]
#y = ['yes', 'no', 'yes']  # Error: Labels should be numeric
#model = LogisticRegression()
#model.fit(X, y)

#Answer#

from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]  

model = LogisticRegression()
model.fit(X, y)

print(model.predict([[3, 5]]))




from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  
le = LabelEncoder()
y_encoded = le.fit_transform(y)

model = LogisticRegression()
model.fit(X, y_encoded)

prediction = model.predict([[4, 7]])
print(le.inverse_transform(prediction))

[1]
['yes']


In [6]:
#6.import pandas as pd
#from sklearn.preprocessing import OneHotEncoder
#df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})
#encoder = OneHotEncoder()
#encoded = encoder.fit_transform(df['Category'])  # Error: Data should be reshaped
#print(encoded)


#Answer#

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Category']])  
print(encoded.toarray())


import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df[['Category']])  
print(encoded)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [7]:
#6.
#from sklearn.model_selection import train_test_split
#X = [[1, 2], [3, 4], [5, 6], [7, 8]]
#y = [0, 1, 0]
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


#Answer#


from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print("X_test:",  X_test)
print("y_test:",  y_test)

X_test: [[5, 6]]
y_test: [0]


In [8]:
#7.from sklearn.linear_model import LogisticRegression
#X_train = [[1, 2], [3, 4], [5, 6]]
#y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels
#model = LogisticRegression()
#model.fit(X_train, y_train)


#Answer#


from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  

le=LabelEncoder()
y_trainEncoder = le.fit_transform(y_train)

model = LogisticRegression()
model.fit(X_train, y_trainEncoder)
print(model.predict([[8, 11]]))

[1]


In [9]:
#8.
#import numpy as np
#import pandas as pd
#from sklearn.linear_model import LinearRegression
# Creating a dataset with missing values
#X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
#y_train = np.array([10, 20, 30])
#model = LinearRegression()
#model.fit(X_train, y_train)  



#Answer#


import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

Imputer= SimpleImputer(strategy = "mean")
X_train_imputer=Imputer.fit_transform(X_train)

model = LinearRegression()
model.fit(X_train_imputer, y_train) 

print(model.predict([[7, 8]]))

[40.]


In [10]:
#9.
#from sklearn.tree import DecisionTreeClassifier
#X_train = [[1, 2], [3, 4], [5, 6]]
#y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed
#model = DecisionTreeClassifier()
#model.fit(X_train, y_train)


#Answer#


from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

le=LabelEncoder()
y_train_encoded=le.fit_transform(y_train)

model = DecisionTreeClassifier()
model.fit(X_train, y_train_encoded)

predicted=model.predict([[8, 10]])
print("predictd value:", predicted)

predictd value: [1]


In [11]:
#10.
#from sklearn.svm import SVC
#X_train = [[1, 100], [2, 200], [3, 300]]
#y_train = [0, 1, 0]
#model = SVC()
#model.fit(X_train, y_train)
#print(model.predict([[1, 150]]))  # Unreliable output due to large-scale difference


#Answer#


from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

scaler=StandardScaler()
X_train_Scaler=scaler.fit_transform(X_train)

model = SVC()
model.fit(X_train_Scaler, y_train)
X_test_Scaler=scaler.transform([[4, 400]])
print(model.predict(X_test_Scaler))



[0]
