In [1]:
#1. Why does this feature selection with chi2 fail?
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import MinMaxScaler

X = [[-1, 2, 3], [4, 0, -6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)


selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X_scaled, y)

print(X_new)

[[0.25 0.6 ]
 [0.   0.  ]
 [1.   1.  ]
 [0.25 0.6 ]]


In [2]:
#2.
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

# Error: strings instead of numerical features
user1 = 'action comedy romance'
user2 = 'action thriller comedy'

vetorizer = CountVectorizer()

X = vetorizer.fit_transform([user1, user2])

similarity = cosine_similarity(X[0], X[1])

print(similarity)

[[0.66666667]]


In [3]:
#3.
from sklearn.decomposition import PCA

X = [[1, 2], [3, 4], [5, 6]]
pca = PCA(n_components=2)  # more components than features
X_new = pca.fit_transform(X)

print(X_new)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


In [4]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

ratings = np.array([[5, 3, np.nan], [4, np.nan, 3]])

ratings = np.nan_to_num(ratings, nan=0)

similarity = cosine_similarity(ratings)

print(similarity)

[[1.         0.68599434]
 [0.68599434 1.        ]]


In [5]:
#5.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings("ignore")

X = ([1,3,4], [4,5,0], [9,7,48])
y = (2,3,5)

selector = RFE(estimator=LogisticRegression(), n_features_to_select=2)
selector.fit(X, y)  # Error: X and y not defined

print(selector.support_)
print(selector.ranking_)

[ True False  True]
[1 2 1]


In [6]:
#6.from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

items = ["action movie", "romantic comedy", "sci-fi thriller"]

vectorizer = CountVectorizer()
vectors = vectorizer.fit_transform(items)

similarity = cosine_similarity(vectors[0], vectors[1])

print(similarity)

[[0.]]


In [7]:
#7.
from sklearn.feature_selection import SelectKBest, f_classif

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1, 0]  
selector = SelectKBest(score_func=f_classif, k=1)
X_new = selector.fit_transform(X, y)
X_new

array([[2],
       [4],
       [6]])

In [8]:
#8.
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

ratings = np.array([[5, 4, 3]])
cosine_similarity(ratings, ratings)

array([[1.]])

In [9]:
#9.
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, chi2


X = [[1, 2], [3, None], [4, 5]]
y = [0, 1, 0]

pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy = 'mean')),
    ('select', SelectKBest(score_func=chi2, k=1))
])

pipeline.fit(X, y)

print(pipeline.named_steps['select'].get_support())

[ True False]


In [10]:
#10.
from scipy.sparse import csr_matrix
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import MinMaxScaler

X = csr_matrix([[0, -1, 3], [0, 2, 1], [3, -1, 0]])
y = [0, 1, 0]

scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(X.toarray())

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(x_scaled, y)

print(X_new)

[[0. 0.]
 [0. 1.]
 [1. 0.]]
